NAME: "SegNet_ASPP"

SEED: 0

DATA: 
  ROOT: "/path-to/VOCdevkit/VOC2012"
  MODE: "train_weak"
  PSEUDO_LABEL_FOLDER: ["Generation/Y_crf", "Generation/Y_ret"]
  BATCH_SIZE: 10
  CROP_SIZE: (321, 321)
  NUM_CLASSES: 21
  
MODEL:
  FREEZE_BN: False
  DAMP: 7 
  LAMBDA: 0.1
  DCRF: [4, 67, 3, 3, 1] # DeepLab-V2-ASPP
  LOSS: "CE_CRF"

SOLVER:
  LR: 2.5e-4 
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-4
  MAX_ITER: 20000
  GAMMA: 0.9

WANDB:
  MODE: True
  NAME: ""
  PROJECT: "BANA"
  RESTORE_NAME: "run_name"