NAME: "Generation"
SAVE_PSEUDO_LABLES: True

SEED: 0

DATA: 
  ROOT: "/content/VOCdevkit/VOC2012"
  NUM_CLASSES: 21 # For VOC
  MODE: "train"
  
MODEL:
  WEIGHTS: "/content/drive/MyDrive/MLRC_BANA/pretrained_models/ClsNet.pt" # From Stage 1
  ROI_SIZE: [None,None]
  GRID_SIZE: 1
  BG_THRESHOLD: 0.99
  DCRF: [4, 55, 3, 3, 3]
