NAME: "SegNet_VGG"

SEED: 0

DATA: 
  ROOT: "/content/data/VOCdevkit/VOC2012"
  MODE: "train_weak"
  PSEUDO_LABEL_FOLDER: ["Generation/Ycrf", "Generation/Yret"]
  BATCH_SIZE: 20
  CROP_SIZE: (321, 321)
  NUM_CLASSES: 21
  
MODEL:
  FREEZE_BN: False
  LAMBDA: 0.1
  DAMP: 7
  DCRF: [4, 121, 5, 3, 3] # DeepLab-V1-LargFOV
  LOSS: "CE_CRF"

SOLVER:
  LR: 1e-3 
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-4
  MAX_ITER: 23805 
  GAMMA: 0.9
